updates

diff --git a/problem_template/run/kt b/problem_template/run/kt
--- a/problem_template/run/kt
+++ b/problem_template/run/kt
@@ -130,68 +130,18 @@ cp "$2" stdin0 2>/dev/null
 
 cdir=`pwd`
 echo "Current directory is $cdir" >&2
-echo $cdir | grep -q "/bocajail"
-if [ $? == 0 ]; then
-    cdir=`echo $cdir | sed "s/.*\/bocajail//"`
-    cat <<EOF > runit.sh
-#!/bin/bash
-cd "$cdir"
-[ -f /proc/cpuinfo ] || /bin/mount -t proc proc /proc
-#/bin/mount --bind /dev /dev
-[ -d /sys/kernel ] || /bin/mount -t sysfs sysfs /sys
-kotlin=`which kotlin`
-[ -x "\$kotlin" ] || kotlin=/opt/kotlinc/bin/kotlin
-if [ ! -x "\$kotlin" ]; then
-  echo "\$kotlin not found or it's not executable"
-  exit 47
+echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+kotlin=/snap/kotlin/24/bin/kotlin
+[ -x "$kotlin" ] || kotlin=/usr/bin/kotlin
+if [ ! -x "$kotlin" ]; then
+	echo "$kotlin not found or it's not executable"
+	exit 47
 fi
-export CLASSPATH=.:./run.jar:$CLASSPATH
-"$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "\$kotlin" run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K
-retval=\$?
-echo \$retval > runit.retcode
-if [ ! -d /bocajail ]; then
-  /bin/umount /proc 2>/dev/null
-  #/bin/umount /dev
-  /bin/umount /sys 2>/dev/null
-fi
-EOF
-    chmod 755 runit.sh
-    chroot /bocajail "$cdir/runit.sh"
-	if [ -r runit.retcode ]; then
-    	ret=`cat runit.retcode`
-	fi
-	if [ "$ret" == "" ]; then
-		echo "Execution error - check autojudging"
-		exit 49
-	fi
-else
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-	kotlin=`which kotlin`
-	[ -x "\$kotlin" ] || kotlin=/opt/kotlinc/bin/kotlin
-	if [ ! -x "\$kotlin" ]; then
-		echo "\$kotlin not found or it's not executable"
-		exit 47
-	fi
-	"$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "\$kotlin" run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K
-	ret=$?
-fi
-
-
-# echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-# echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-# echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-# kotlin=`which kotlin`
-# [ -x "$kotlin" ] || kotlin=/usr/bin/kotlin
-# if [ ! -x "$kotlin" ]; then
-# 	echo "$kotlin not found or it's not executable"
-# 	exit 47
-# fi
-
-# "$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "$kotlin" run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K
-# #"$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
-# ret=$?
+"$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
+#"$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
+ret=$?
 if [ $ret -gt 10 ]; then
     if [ -r stderr0 ]; then
 	grep -q "not find or load main class" stderr0
